### ISSUE TITLE
Microsoft Project 2019. Александрович Георгий ПИ 4-3

### ISSUE THREAD

**Issue by George305322** [prikladnayainformatica2024/ITProjectsManagement#26]
Составить тестовые вопросы к материалам главы, исходя из норматива 1-2 вопроса на страницу книги

|стр 407   |
|---|
|Формирование отчётов: расширенные методы              |

|стр 423   |
|---|
|Настройка программы Project                                           |

|стр 535   |
|---|
|Совместное использование: Project, SharePoint и PWA   |

* [x] Написать вопросы к тексту

**Comment by MuseCat77** [comment]
https://github.com/prikladnayainformatica2024/ITProjectsManagement/wiki/Microsoft-Project-2019.-%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87-%D0%93%D0%B5%D0%BE%D1%80%D0%B3%D0%B8%D0%B9-%D0%9F%D0%98-4%E2%80%903-(%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%8B%D0%B5-%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81%D1%8B)
